### ISSUE TITLE
Mermaid Support

### ISSUE THREAD

**Issue by NukaCody** [code-hike/codehike#108]
This may be out of scope of Code Hike, but I'm curious to get your thoughts. Is there plans on implementing [mermaidjs](https://mermaid-js.github.io/mermaid/#/)? So graphs can be rendered alongside with

```
``mermaid
sequenceDiagram
    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!
```

Albeit it may be hard to justify as you can also build diagrams with [mermaid live editor](https://mermaid.live/edit) or plantuml and simply import the image.

Here's an example for others who are trying to solve something similiar

```
Code Hike will apply syntax highlighting to any code block

``js
function lorem(ipsum, dolor = 1) {
  const sit = ipsum == null ? 0 : ipsum.sit;
  dolor = sit - amet(dolor);
  return sit ? consectetur(ipsum) : [];
}


<img src="./assets/test.svg" alt=""/>
```

<img width="509" alt="Screen Shot 2022-01-11 at 12 03 02 AM" src="https://user-images.githubusercontent.com/30978270/148884235-b61826b1-034f-44cc-86a2-6665ccc53d2e.png">

**Comment by pomber** [comment]
Hey, I think there are remark plugins that already do that. There are some places where I want to add more *extensibility*, allowing the user to pass custom components as children to CodeHike's components, I'll try to make sure that it plays nicely with mermaid codeblocks.
