### ISSUE TITLE
[mdx] Support more comment syntaxes

### ISSUE THREAD

**Issue by pomber** [code-hike/codehike#109]
We only support `//` syntax for comment annotations. Maybe we could use [vscode-textmate](https://github.com/microsoft/vscode-textmate) directly to find any comment content for any supported lang.

**Comment by Mayank-Sh07** [comment]
@pomber Why not have a globally supported comment annotation? 

For example 

```python file.py
// focus
inputOne = int(input())
inputTwo = int(input())
```

does not work with python, instead I'm required to detect and change the comment character to `#`. Supporting `//` or maybe some custom character across all languages would make it easier to separate out the codehike notations from the actual code when not relying completely on the metastring syntax.
