### ISSUE TITLE
bug with the new linenumbers feature?

### ISSUE THREAD

**Issue by cabljac** [code-hike/codehike#112]
Hey there, was testing out your new line numbers feature in the pre-release, just with some codeblocks identical to the demo examples, seems to break some of them, unless i've done something wrong - 

I just included the option `lineNumbers: true` and updated to `"@code-hike/mdx": "^v0.3.0-next.20"`

<img width="645" alt="Screenshot 2022-01-17 at 10 19 16" src="https://user-images.githubusercontent.com/32874567/149751726-5c609438-4157-44d5-8b15-a3c9653de5f3.png">

**Comment by cabljac** [comment]
this could be due to some extra styling im adding somewhere, will double check and get back to you.

**Comment by pomber** [comment]
Yes, please, if you have more info post it. Does it happen only with `lineNumbers: true`?

**Comment by cabljac** [comment]
no it seemed to happen with or without, and the content *is* there, just hidden under some overflow

**Comment by pomber** [comment]
If you could share a minimal repro I'll debug it

**Comment by cabljac** [comment]
I'll try, just a sec :)

**Comment by cabljac** [comment]
OK bug is with my code not codehikes, thanks for the quick response anyway!

**Comment by cabljac** [comment]
I believe it's some clash with my tailwind styles, but there's too much going on to set up a quick repro rn

**Comment by pomber** [comment]
Let me know if you still need help, also if you find the problem let me know, I want to try to prevent similar issues.

**Comment by cabljac** [comment]
seems to be working now, i think it was actually a cache issue
