### ISSUE TITLE
[mdx] Code has extra padding when using with tailwind's prose

### ISSUE THREAD

**Issue by pomber** [code-hike/codehike#115]
![image](https://user-images.githubusercontent.com/1911623/150804504-2dcaf2ba-f11c-41f7-a17c-40af03efde9e.png)

**Comment by cabljac** [comment]
ah i ran into this, i ended up adding some css to remove the padding, nice

**Comment by DanielFGray** [comment]
I have also noticed some interesting padding/margin issues with tailwind prose
![1643485620-369x555](https://user-images.githubusercontent.com/410447/151675429-89924a9c-6f95-4d36-8b86-5f0553b45027.png)
specifically that code blocks followed by an `h1` (but not h2??) are missing some top margin

also, and this may not be `prose` related, but it is difficult to get spacing between two CH blocks that are direct siblings

**Comment by pomber** [comment]
Try version `0.3.0--canary.116.9a0c186.0` if you can and let me know. I made several changes including adding the `not-prose` class and also default vertical margins. I changed some `ch` classes, so if you had custom CSS it may stop working.

**Comment by pomber** [comment]
I'll close this one but let me know if you see something wrong with tailwind + codehike

**Comment by cwlittle** [comment]
Codehike is overriding specified font sizes with media queries from tailwind.
```
 <article className="prose-stone prose md:prose-lg md:prose-code:text-lg">
  <MDXRemote
    className=""
    {...content}
    components={components}
    style={{
      boxShadow: "none",
    }}
  />
</article>
```
In this case `md:prose-code:text-lg` works without CH, but not with.

**Comment by pomber** [comment]
font-size for the code is a special case, you'll need to add a specific rule to override code hike style
