### ISSUE TITLE
Update next.js example to use `@next/mdx`?

### ISSUE THREAD

**Issue by AlexFrazer** [code-hike/codehike#119]
Looks like it's what the official docs recommend

**Comment by pomber** [comment]
Last time I checked `@next/mdx` wasn't using MDX v2. I used the guide from the [MDX docs](https://mdxjs.com/docs/getting-started/#nextjs).

**Comment by AaronLayton** [comment]
I am using `mdx-bundler` as it gives more flexibility

**Comment by marckraw** [comment]
@AaronLayton is naming files and `CH.Code` component works for you in `.mdx` files if u are using `mdx-bundler` ? I'm also using it, with `nextjs` and it doesnt work :(

**Comment by pomber** [comment]
It should work. Check the examples folder in this repo or provide a sample repo please. Thanks.

**Comment by marckraw** [comment]
@pomber just did, and fount the issue, it doesnt fully work for react@18, with react@17 everything works great :)

**Comment by pomber** [comment]
oh, yes, I need to fix #161

**Comment by pomber** [comment]
The example now uses `@next/mdx` https://codehike.org/docs/installation/nextjs
