### ISSUE TITLE
Unsupported style property color-scheme. Did you mean colorScheme?

### ISSUE THREAD

**Issue by MarkusWendorf** [code-hike/codehike#132]
I get the following error message using codehike (0.3.0-next.24) with next.js (I can provide a github repo if necessary).

```
Warning: Unsupported style property color-scheme. Did you mean colorScheme?
```

Should be related to https://github.com/code-hike/codehike/blob/efa7caac0350241ae662cae5126ddcd7a627a1a8/packages/smooth-code/src/code-tween.tsx#L150

**Comment by pomber** [comment]
Oh, thanks. It's just a warning, right? I'll fix it in the next release.
