### ISSUE TITLE
[Feature Request] Copy button

### ISSUE THREAD

**Issue by daoleno** [code-hike/codehike#138]
Great project! Can we have a copy button in the code editor?

**Comment by pomber** [comment]
Yes, that is something I'll add soonish.

**Comment by cabljac** [comment]
ah awesome :D

**Comment by marcelgruber** [comment]
Can't wait for this!

> _Bugs’ genitals are called copy & paste. That’s how they reproduce._	
> 
> \- Alex Ewerlöf
