### ISSUE TITLE
Looks good on local but doesn't work on Vercel deploy

### ISSUE THREAD

**Issue by marcelgruber** [code-hike/codehike#153]
All seems to work well on my local, but when I deploy to Vercel, it doesn't work.

**Local**
<img width="862" alt="Screen Shot 2022-04-08 at 10 05 52" src="https://user-images.githubusercontent.com/4956028/162480424-b7e5915d-d45f-4af6-842e-6f6b7e010c84.png">

**Vercel**
<img width="721" alt="Screen Shot 2022-04-08 at 10 05 57" src="https://user-images.githubusercontent.com/4956028/162480431-260b6dd3-b6ab-4f5e-a592-da0797cd7cc9.png">

**Inspecting Vercel**
<img width="2067" alt="Screen Shot 2022-04-08 at 10 08 03" src="https://user-images.githubusercontent.com/4956028/162480625-aace0404-75ad-43f8-aebf-99ef6e2b6013.png">

What's odd is that when I click the "tab", the code shows for a few seconds but then disappears again. 

Nothing in the console indicates any issues.

**Comment by marcelgruber** [comment]
Thanks for the quick reply! I added you as a collaborator to the repo so you can see.

Here is where I import the CSS.

<img width="874" alt="Screen Shot 2022-04-08 at 10 15 24" src="https://user-images.githubusercontent.com/4956028/162481645-da0cff58-d5e2-4ef1-bcde-848d606cacb7.png">

**Comment by pomber** [comment]
Hmm, I've used Next.js + Tailwind + Code Hike + Vercel multiple times without problems, so in theory, it should work. 

I'll try to investigate when I have some time. It would help if you could try to find a minimal reproducible example.

**Comment by marcelgruber** [comment]
Thank you. I'll keep hacking away. It's probably something silly.

**Comment by marcelgruber** [comment]
I see the issue. I'm using postcss to purge unused CSS. There isn't a way to exclude entire imports at this time. For example, this doesn't work:

```
/*! purgecss start ignore */
import '@code-hike/mdx/dist/index.css'
/*! purgecss end ignore */
```
There's an oustanding issue for this and the feature is scheduled to be released in a later version:
[https://github.com/FullHuman/purgecss/issues/170](https://github.com/FullHuman/purgecss/issues/170)

postcss does have a way to do this by specifying certain selectors to ignore, but the styles for Code Hike don't share a common ancestor class, so there isn't a way to do this reliably. 

Solution 1: move the code hike dist CSS into the project and import that and wrap the CSS in ignore comments
Solution 2: don't use postcss 
Solution 3: add a common ancestor style class in Code Hike (though this will add bloat)
Solution 4: identify all parent classes in Code Hike and add them one by one to the ignore selector list in the postcss config

I chose solution 1 for now.

**Comment by pomber** [comment]
I think all the code hike classes start with `ch-` maybe you can use that together with purgecss's `whitelistPatterns`
