### ISSUE TITLE
Responsive code window in mobile device ?

### ISSUE THREAD

**Issue by nurmohammed840** [code-hike/codehike#164]
I don't know how to explain, But in this first example on mobile device, Font is very large (like 14) But I want to show 2nd example on mobile device, and hide scroll bar, 

Documentation is not very helpful, And I have no idea what to do... 

I also want to change button (next/prev) style.

<img src="https://user-images.githubusercontent.com/46383294/164838026-450a116e-bb1d-43aa-9a15-39552b3155f8.png" style="width:150px;"/>
<img src="https://user-images.githubusercontent.com/46383294/164838044-d9bea44c-e44d-4670-9ee8-10336a7f877d.png" style="width:150px"/>

I just want to show all code, without scrolling, On mobile like devices...

**Comment by pomber** [comment]
A live example of your issue would be helpful.

Have you tried adding custom CSS?

**Comment by nurmohammed840** [comment]
Modified many internal CSS styles  using, chrome dev tool.  Like:

-  aspect-ratio in `.ch-slideshow-slide` style
-  height and width in `.ch-code-scroll-parent` style
- font size/width, line height etc... in `.ch-code-scroll-parent` style 

Those style doesn't make it responsive, And I have very little knowledge about CSS

**Comment by nurmohammed840** [comment]
@pomber, Here is a [live demo](https://nurmohammed840.github.io/tftp.rs/Decoder.Request.html)
