### ISSUE TITLE
Height frozen in multiple filenames

### ISSUE THREAD

**Issue by pedrosousa13** [code-hike/codehike#184]
Hi! 

We're having an issue where the height is not dynamic on multiple filenames. It adds scrollbars to both x and y axis.
Should it maybe expand automatically? Or we could have an option for that specific case.

Here's a video with the issue

https://user-images.githubusercontent.com/4235827/169536978-5a001a80-1213-4565-92e9-5b30acc70c67.mov

.

**Comment by pomber** [comment]
Yes, that's kind of intentional. Sometimes you don't want elements that expand vertically because it shifts all the elements below. 

But I understand sometimes you do want the element to expand vertically. So I'm still looking for the right solution. 

For now, one workaround could be to set a bigger height manually. In Code Hike v0.5.1 that would be `<CH.Code style={{height: 300}}>`. I know it's not ideal.

**Comment by berber1016** [comment]
I had a similar problem，Using `<CH.Scrollycoding>` and `<CH.Code>` causes the second file to be highly locked and unable to scroll，
such as:

```
<CH.Scrollycoding>
// some text...
<CH.Code>
// the issue description in here,the first file line is 10,the second file line is 30
</CH.Code>
</CH.Scrollycoding>
```

**Comment by pomber** [comment]
@berber1016 can you provide an example (you can try the new playground: http://play.codehike.org/)? inside Scrollycoding the height should behave differently

**Comment by berber1016** [comment]
@pomber  Yes, you can click [this link](https://play.codehike.org/#N4IgtgJgHiBcIGIEAIB2BTA7sgagV3QAoBKAHVXIB4BhACQDoBlAYwCcB7AG04E9n2IAS1QBzAHzlyAZ3Zh0yCOiltBABwAug9qnq69VOvWoD5E1AANLAKynI8U9AHphiqPRvlBYVe1brcBMgAZhxgyADkAG4E4QDckqic6P4AhqqqyAC8aFgBRMDkyEXonLARCGmq4QA0hUUQKeopZQWoRe1yUlIpIuhl4bQlnOx5AIThdcgAvuRTZBQWluSW5jbI-KxOLuhua0HszPaZAIwATLDHAOzkQXiozJraeYTsGlqoUsTIre3IgkHIQiTX7IVQcZhKKT0dCoSL0AByAHkACIAUQA+qj4ThkKNMtlwmCBHgHu9wsgAGQU4G-UaEdQAC0EtmEUia93Q7AB+HQ81+Xx+IKKNPamBSrFQhHCPL+thS620bNYJPUvmQKVQEGQUgZ7DwnC1ACN5MwUtx0FrMIJGchGfJzBhMOZkABrdA8TC+CDhPntGZtdqORx-VDWgCygigwmQYEj0fRwmttpGPPoRNV6h4qnQ9ATofUJHiAaKjOZucTBdejw+839FYjUclPPmbMa6AbwkIzfI6EiMPUUg7TYI804-3QzD4SSHXZH5E2mvQrBn3cW5gSlEchmMijMCQAtIfkNJZPJFMpWGpq3p9AsVmsNltF7tbPtDlJMgBOC4ABmWSwWTdDBYDhuD4ARhHEEBqhAZgujgEA002SJBCwfd+FQJphCXb5jwDMBxREYQygADlUKBYjwqZoNg7QgkEEQ4FAMcMHhPAwGNVgpDgIIzQcGCdXYTBjFUHgACE8HUVVUB4vj0Bgu05AQgj1CXQQzX3BpWDdVgQCmKYgA) view this problem.



when you activing first paragraph on the left,change active second file, you can not scrolling the second file.
![image](https://user-images.githubusercontent.com/31471551/170642046-ad053927-54ba-46af-ad54-df43aff6cd16.png)

**Comment by ndom91** [comment]
I'm having a similar issue, the `<CH.Scrollycoding>` component's height seems to not adjust correctly when more text is eventually shown.

Demo: https://next-auth-git-ndom91-upgrade-to-mdx-v2-nextauthjs.vercel.app/configuration/initialization
Code: https://github.com/nextauthjs/next-auth/blob/95d9263954970c4d13e434bb86adbedcd566bc99/docs/docs/configuration/initialization.mdx

**Comment by pomber** [comment]
@berber1016 the reason the second file can't be scrolled is the `focus=12:17`, if you remove it you'll be able to scroll.

@ndom91 and @berber1016, the height of the code in the Scrollycoding component is the max between 200px and the height of the first step code. You can change that 200px with `--ch-scrollycoding-code-min-height`. See the CSS `--ch-scrollycoding-code-min-height: 80vh;` in this [demo](https://play.codehike.org/#N4IgtgJgHiBcIEkB2ACAcgUygFwHQCsBnAGhQE8B7AVxQGMBDVCDAMwEskMVGUBBABQQoATtWxdsAC3rYUAdzYAbRXRm1J3ZSIwBHKhkLZCKKTJQAjDAHMO8tlO50Mw7PVsAHGZNwoAwhSQANwwkNhDsRTJSKTZjWNVlDAgUAG1fNQ16LQEhUSpxQgBdAApJbGx3QlgAemrOHCJcCmEraogKWkJq+nc2AFo8grayJHowNlo+nv7BgwBiBmx1KeUp3oGxAwBKXAAdJH2AdUkQ8moUZnZORwADas8rA27e7vzJapTcL-rXN8KblAAKQAytUACrAlDsRQYUiUGgcQzCKi0WSYHC8N4EYymWQYYLCMh8QTaPQGWSWGxIUJIKx2Bx3aavKTVABUAMIkmoimSlhQ0iQEBhvKJUi4tAozHkwns4lQtjFKBun2+WF+Un+UKUGD2ByQABEMO4QhAOHSAmcqMIUFRCOL6Ha4ecGPLQtg2Fk2AAvLjo7CYqTYlAKuQUC5sFgsZzheT0MhVfb7AA8vgAErhgbRRMoyBLTbSAHyJpBzOYoYFsMDuGHBt0exTemRsALF5AoMAUQyqO0kS3yAIAclknCSJjDoeEhO45jE8mkshufoD3iIAPaBlIjGS8LsWkeFKJ+FtsiuXAUDkVLAoygoClptfs9cb7oCsGLNw-RhQ93ojy6TPoN4Pi+XAfkAjVcC-K9aFtABeABGfZK3cZo0TVZcoVEMAUF2EAfimN5cOLLAUJcC5WEAxQ0IxN5imAfYUBQED9gAXy2fYPxuYtU2jJ0aACSIUBHZJsDDTxCGMeFrRSCh3BfJAimKaoJSQdgrCtJsAmqWT5MILYxyVJc3huTdBUM9DjIuCgDBME5tEMXV9jBSR4niRV3GEVhnE85IOEfT0vU010THyZp6y6CgxWtTwXGMCgWFsrh2hgsBwiCzc4lkQhkIbdgbMVPMuC3bQIBRGyULld0shQbzmjiVBFXAk4kHdRZm1QFhFFvRySzLXgIECRhaFHPyqobQL5NbBKd2kYJHEIY1aAjCYbTtbsirM4SDLAegAGtfQswMiCslBCAoVKYnvQgGysMpBNNSNoxa2yeDkedg1keJmGyqxOGSK9hFIfajVrdsOAgaI7OVECwL+bEARUtStRreJDCUFQjy7VlWXobR1MUehpJyFAACVNhKMoKiqWofkaZpWmS-91lmLoOGwURStRdqtmx7hZEVE0UHixKLjjHq+gl4tnLMQg3AhvsXQfMbvQOmijuMBt9ts2I3z1Tivx-P9njYZl3hVUC1SawpIOMcwrFggA2WAAA4kKrVCTDIY0UGAdB0N6EndH0QxSCXAODBQhSuBYzDzpwvC1SI0J3bIoyHBYLD4-wpqk-2EiPcuSjZAdEZaChKgkC5i0muKTydFgP2MXDskQ-shuw7YQOFoCO19Po1Bv2qFB9XHed8WcPs5EYWQTk80hLABiQ7Lr4PPuMcS7WSdo5AasNF0OyQuIHzzsCtVB6Cn+xG-9Wi69ITze37xjGOYge2NYjiPylqGQI5DAq9QAoLQaMtB8ikqkHS7VFLKQCGpDS8ltJySgVsee+Q+xIFvPyegc13KdmyuYJQ9hRRhiwP-fIGBqgdgekSYaLg3ANRcrSOKDCuAr3JD1AAms6bk-1mg1SgGMasXAup0kVGw1u9AIDJBOJI5wvZPKSKVGSQkAI+E3BnBAMgAIYpjAwOIYQvY3oyHHtaHcoYqA8hOrYHgxNZji0lnqXgSAiSDRlPQcwNYdxZgwMY7Wxgp5EiASoPk2C3AEw8VwBUUM06HyFkgnu3B-EYGUKQbKlcl4YCJITSJLDTq6NOhKY0PV9bGENk8ACQFzawwgkYN2pF+Zey4L7DugcW7YFDv7TuEce7R1jthXCPwk7IQ9jEvpWc1QESkLneo9TyIsCLok0u5dK7yW4LfXQ7dOmtNXvfAwmym5dO7lHPuxZGIRlrroXAyiyAWxwE1XAHBaCKCoN9YouEGDKHMPQWgu1cL6QAGT-NJLgC6XJkiwQhfHfgAB5YEYI-k+wYs-FSZ0YS4BEW8gez946pi3A2e8HzFBfJ+aSVeYywBEgQMwFqRCUD8FEIENgzBhC4WIEi7FddcAaLIOylA7E36nMHigAA4noxwMFDBxwlBQXaYQUCDWeVwDOccxFB3JEilFWVzoYH8DKuVsFgXStlQYFIuEzqpT6BK0SYBLUUD1RgXChRBUnzPtwS+1Eb5SAuToXZj9eWv2xYS4lu0qiIqxc-Hs2UAh0VOgYKNSBogytOGxMN2LsW1FJno11uMjVyoVfoRJKAYqyGFoqSN7VeXpqHs5VyxgFHJDeqcG4nLrm3PVN4R5zzXlmrjRWkAAKgWctBZKFAEKDW4WFQAUXhSAI+aaI29oCLgc1Oq7XGtHadbVurjWVufi64QqBy0tnDYxFivKz1v35RezixYJZ9GLLwItwhvmtWqlgQRNYJQWN5BIMMGCspcjkOK5wrgPAMqZRPC0ipC4WKymwX6fQPC-lhBYNBIDglFQiQZH6wVzwaHsD4YozlInMFxm5PapxlXYRSDEYwppCASvjRTcolQajVBsFIKg5hcASjAHUS2bwiD8ZwJM949HGNQOqAAZnglJqTWwti60-jcY6ZSmYmyasBVUdy4a1OTrM0ZVHxkiZziAOpHtfA+XCOFelFBGXMrGQMiZmmPJ2YgwY5SVmaVZEIEMlOshhV2qsDCWz9mJ5GacyZoCrmwseasEFmE0z85kRg1RRZldlkALWV6u+9kTkD01U+tzzLjAGtNeGyzSRrM+dC+54oIEUG8sCxQYLGBavMvq18RrA8nV6kYoV2Ihp5mwYrL9Dg-BkMbqHXosFo7IUTunbhFAgLgWtuqR2yuXaDBvJADhjgfzBUZsOOjfkEGRY3Ga619rzgASNtQDuRl2UFzG1NtUPbSA53BgSsUQbFERvwZpBNx4+kYvucILgFC7hij8qRfu8+7rr7Lm9b60gT9n6g5K2y8NAaUDvyQNer+eo73FiTNUNMGYszXkiHmM0RY9QADE+Edk8uRUDihmGaBUKEpQ7iawvqgdwMyb0JgaGHRAYw2TTpUHcPUpIpAhEOnFCcEls5FQpBJpOuFxIhDJSoKlFqQUSjsb0e6WkfRDCE3EBAaoD9sBrDYPpPhjUZeiA8h6cQ3AFGgxo3ZM6Vphp0ElBgZjVM2McckFxnj51hPtqE9nICHiKDmEofQn8PzkNdHjyyQgwhaAwM8tUcGWAbYw6QDW-xcYhYJVGk+L0ZpzJq1ifEAkRIUJyGcCwCxqCAM8IsFwW0o4FqEzNJEHqjPrTM6SnosJHOshc8GjzrD-OEnFWF+odsM3JQS5Z4QaXsv5YK7Wuof+u0hZoLVxrrXxNdf69cPJI3+5TdWHN64FwSQbfknt4760zvXNu98dkmRqgD7lwH7rnuKEHiHqxrUOHpHrxjHk1HHs5gnl1MnjtBwGnrtBnjHqJm9rnvnhQkXlACXt-PEAElXkrLXvXvvI3gCM3s4K3reB3l3qhj3t+n3qtIPjFCPjcsWOPu2M0FPmzrPloNzuEnzgAhLkLi5OvmLtvqAXvqhHLkWjCIrnQMrqfqrnZOrprmCNrlZClGlPfkpI-maC-pbu-rbl-kLD-nZD0H-m4h7oAd7mWtQOAYHswFAdTOxvYBHtxvAetkgVFiyInmganp4OnkbFnu8DnnnhKAXkQSQXqOXrGESMLDXgFNQTEnQcYC3kWkwcIJ3ooN3qdFyOwXyAPskEPjKLSKPnwUzoIazjPkLOfKIQvuIUVJIYLg2jIaLpvuLp7goTLkoQfqoUfhoWfvzNoZfnodfh0HrkYe1A-ibmYRbm-tblYdMN-iLPYa7o4UVF7rYCAZuv7hAZ4aUCxt4bAf4dHoEZnsgSEagSnhgREVgVEQ8TEfgfEYQYKMXkYKXikeQekXWJkfeDQZ6k3rkQwfke3oUSweYGhmUZYhUZvKdNwbUbwQzg0SzswMIS0ZztwO0bzp0bpN0XOCLhvlIFvoMVLsMesfLmMUrifpMSLDoVfiSDfosQEMseUKsa-lbh-oYNYU7nYS7rJPsYMUAakK4acR4cHhcaHjAb4XAbcQJlIEEXbppqEc8UgJgdgdEXgXEYIYXr8cQf8aQRXmkdXiCeNFkQfDkfKtCW3swcUawaUb3iiVwcPhibqCAMQCAJ0IQHACABDp5IyhgHILagbhwBPL7EijtC0BwA3M7O4FAAANw4QDwSzLAMbZjU6ShmGFR9DjBIB9AnDwZlDJkAAMgQkgaZrEfpAZsC8GcAoA+KGAaAeulgBicA8y7OsIu2gG-g7gZAAAQvkKJEgL2T5gOWKKlMGTtPovWH0BAITPtMICACxCxEAA). 

I'm still working on a smarter default height :)

**Comment by pomber** [comment]
BTW @ndom91, I'm using NextAuth.js for codehike.org, let me know if you have any issues or requests.

**Comment by ndom91** [comment]
> BTW @ndom91, I'm using NextAuth.js for codehike.org, let me know if you have any issues or requests.

Thanks a lot, the css var for min height did the trick. We were thinking about adding it to the docs, really love the scrolly coding thing. But tbh we just don't have a great use-case for scrolly coding. We have very few (if any at all) docs pages which start with 1 file and then progressively add things, highlight, etc. that same 1 file.

However, in general I really like the highlighting, bg, notes, etc. of codehike as well. Maybe we'll use it for just those anyway!
