### ISSUE TITLE
Playground Not Working on MacOS

### ISSUE THREAD

**Issue by Aiyush-G** [code-hike/codehike#194]
On Safari Version 14.1.2 (16611.3.10.1.6) on MacBook Pro running macOS Big Sur V11.6 there is a playground error: 
```
Compliation Error:
Can't find variable: BigInt64Array 
```
<img width="1425" alt="Code Hike Playground Compilation Error" src="https://user-images.githubusercontent.com/55917505/172638893-b01bbae0-2b03-4f9f-9309-e45d310778d5.png">

On Chrome, however, it behaves as expected.

**Comment by pomber** [comment]
Ups, thanks for reporting. Looks like it also works well on Safari 15.

This may be the cause: https://github.com/code-hike/codehike/blob/16fc2560e87aff07140e4bdabcf92953d07028b8/packages/mdx/src/remark/to-estree.ts#L148

**Comment by pomber** [comment]
Try https://playground-git-safari-playground-codehike.vercel.app/
