### ISSUE TITLE
CH.Slideshow with columns

### ISSUE THREAD

**Issue by pomber** [code-hike/codehike#207]
We should make Slideshow easy to style in two columns, maybe like this [tutorial from Algolia](https://www.algolia.com/doc/onboarding/#/pick-dataset).

**Comment by brianespinosa** [comment]
I ran into some issues with this on my end while working on my presentation. Are you thinking we want to add more configurability with css custom properties for these things? If so, I could go through and expose a lot of different parts of the existing CSS using custom properties at the same time.

**Comment by pomber** [comment]
@brianespinosa don't worry about this one, it's a placeholder for some ideas I have. But tell me about the issues you had.
