### ISSUE TITLE
Allow code snippets to be in separate files

### ISSUE THREAD

**Issue by alpinegizmo** [code-hike/codehike#211]
We want to keep the code examples used in our documentation in their own files so we can use a CI/CD pipeline that tests that the examples actually work. For example, we've done this in the past with CodeSurfer:

```mdx
```java 1:7 file=../examples/example.java
```

And with Docusaurus, this works:

```mdx
import Tabs from '@theme/Tabs'
import TabItem from '@theme/TabItem'
import CodeBlock from '@theme/CodeBlock'
import KafkaSinkSQL from '!!raw-loader!./KafkaSink.sql'
import KafkaSinkJava from '!!raw-loader!./KafkaSink.java'

<Tabs>
<TabItem value="sql" label="SQL">
<CodeBlock language='sql' default>{KafkaSinkSQL}</CodeBlock>
</TabItem>
<TabItem value="java" label="Java">
<CodeBlock language='java'>{KafkaSinkJava}</CodeBlock>
</TabItem>
</Tabs>
```

Perhaps this can already be done somehow with codehike, but if so, I haven't been able to figure it out.

**Comment by pomber** [comment]
That's something I'm planning to add soon :)

**Comment by pomber** [comment]
The syntax will be like this:

````md
```py
# from ./assets/foo.py
```
````
