### ISSUE TITLE
Next.js fast refresh doesn't work

### ISSUE THREAD

**Issue by ghoshnirmalya** [code-hike/codehike#212]
When I add the following code, fast-refresh breaks:

```c
```python mark=1[22:30]
print("Rendered with Code Hike")
``` 

Without the above code, fast-refresh works as expected.

[Here's a link to a similar issue.](https://github.com/vercel/next.js/issues/13574)

**Comment by ghoshnirmalya** [comment]
This issue isn't present in the contentlayer example.

**Comment by pomber** [comment]
How are you using it with Next.js? What do you mean that it breaks? The page doesn't refresh or the state is not preserved? An example repo would help.

**Comment by ghoshnirmalya** [comment]
> How are you using it with Next.js?

I'm using [this example](https://github.com/code-hike/codehike/tree/next/examples/nextjs). 

> What do you mean that it breaks?

When I make a change in the markdown file, the whole Next.js page gets reloaded and then the new changes are visible. The new changes should be visible with hot reload.

**Note:**
This isn't noticeable in the [Contentlayer example](https://github.com/code-hike/codehike/tree/next/examples/contentlayer). In that example, the changes show up without a page reload.

**Comment by pomber** [comment]
OK, I think I know why this happens. I'll try to fix it soon.

**Comment by pomber** [comment]
ok, it isn't easy to fix. I'm going to leave it for later.

**Comment by ghoshnirmalya** [comment]
No problem.

**Comment by neongreen** [comment]
@pomber can you share any details re/ why you think it happens?

**Comment by pomber** [comment]
> @pomber can you share any details re/ why you think it happens? I'm hitting this as well.

There are some useState I need to remove from a few Code Hike components, but it isn't a trivial refactor
