### ISSUE TITLE
How to integrate with `next-mdx-remote` 

### ISSUE THREAD

**Issue by tmkasun** [code-hike/codehike#222]
First, Thank you for maintaining such a nice code highlighter, I tried to integrate `codehike` in my blog site which uses [`next-mdx-remote`](https://github.com/hashicorp/next-mdx-remote) for rendering the markdown, But I got errors while trying to integrate the codehike.

I'm using the `serialize` function from [`next-mdx-remote`](https://github.com/hashicorp/next-mdx-remote)  and getting the markdown content and passing it to the `MDXRemote` component.

This is my config (with `codehike`)

```js [slug].tsx
.
.
.
export async function getStaticProps({ params }: Params) {
    const { remarkCodeHike } = require("@code-hike/mdx");
    const post = getPostBySlug(params.slug);
    const mdxSource = await serialize(post.content, {
        // Optionally pass remark/rehype plugins
        mdxOptions: {
            remarkPlugins: [[remarkCodeHike]],
            rehypePlugins: [],
        },
    });

    return {
        props: {
            mdxSource,
            post,
        },
    };
}
```

With that, I got the below error

![image](https://user-images.githubusercontent.com/3313885/178147134-3d1a0b2d-4ea7-4b33-9c7d-f76e06165174.png)

since it's saying `_missingMdxReference ` I then wrapped the pages from '@mdx-js/react' [<MDXProvider />](https://mdxjs.com/docs/using-mdx/#mdx-provider) 

After wrapping with the `MDXProvider` component I got this error
![image](https://user-images.githubusercontent.com/3313885/178147325-990f2e45-ecdb-48b8-add9-b8e5825dfbc4.png)

Can someone please help me to integrate codehike with `next-mdx-remote`

Thanks in advance

**Comment by pomber** [comment]
Hi, thank you.

There's an [example here](https://github.com/code-hike/codehike/tree/next/examples/next-mdx-remote). Since next-mdx-remote doesn't allow imports the configuration is different, the important part is in [this file](https://github.com/code-hike/codehike/blob/next/examples/next-mdx-remote/pages/index.js).

**Comment by wooorm** [comment]
P.S. Some of the things `next-mdx-remote` does can also be done by MDX itself (see https://mdxjs.com/guides/mdx-on-demand/ for more info). If the problem is imports, perhaps that can be sidestepped with this (which does support imports)?

**Comment by tmkasun** [comment]
Thanks, @wooorm  & @pomber It worked!

https://me.knnect.com/blog/apim_320_customization
