### ISSUE TITLE
Parse Code Hike headings anchors in Docusarus TOC

### ISSUE THREAD

**Issue by evanorti** [code-hike/codehike#226]
Scrollycode allows you to write explanations with markdown headings. Docusaurus turns headings within Scrollycode into heading anchors, but they don't appear in the auto-generated TOC on the right of each page. Markdown headings outside of Code Hike sections still render in TOC as normal. 

Generating Code Hike headings to the TOC is important for easy navigation. 

<img width="935" alt="Screen Shot 2022-07-15 at 9 27 29 AM" src="https://user-images.githubusercontent.com/87997759/179266783-6a478765-fb6e-4ab8-876f-1e5b35db4368.png">

There is a similar issue with Nextra. If you use Code Hike with Nextra, the auto-generated headings feature is broken, and no headings are parsed as anchors, even outside of Code Hike sections.

**Comment by pomber** [comment]
Not sure about Nextra, but the Docusaurus issue comes from `docusaurus-theme-mdx-v2`. 

You can try wrapping the headings inside a `<div/>` and it also won't work:

```md
```

**Comment by pomber** [comment]
Upgrading `docusaurus-theme-mdx-v2` to `v0.1.2` should fix it (for docusaurus)

**Comment by evanorti** [comment]
Awesome! thanks!
