### ISSUE TITLE
Cannot find module '@code-hike/mdx/components' or its corresponding type declarations.ts(2307)

### ISSUE THREAD

**Issue by NekoChanTaiwan** [code-hike/codehike#237]
https://codehike.org/docs/configuration#auto-import

![image](https://user-images.githubusercontent.com/47508893/180930968-67ecb4c3-065a-4895-84f1-4f9439d4644f.png)

| Lib | Version |
| ------------- | ------------- |
| @code-hike/mdx  | "^0.7.1"  |
| typescript  | "^4.7.4"  |

**Comment by pomber** [comment]
Does it break the typescript build or is it just VS Code complaining? A small repo with the issue would help me fix it.

**Comment by NekoChanTaiwan** [comment]
> Does it break the typescript build or is it just VS Code complaining? A small repo with the issue would help me fix it.

It's breaks the typescript build :
![image](https://user-images.githubusercontent.com/47508893/181278797-36ca3a1b-2f98-436c-b6ff-470b706f89bd.png)

And I created a small demo for you : [CodeSandbox](https://codesandbox.io/s/code-hike-path-problem-e7nmsw?file=/pages/index.tsx)
