### ISSUE TITLE
Scroll horizontal shown when using `* { box-sizing: content-box }` (Tailwind base)

### ISSUE THREAD

**Issue by colelawrence** [code-hike/codehike#240]
I fixed this issue by adding the following CSS to my own project to override base tailwind.

```css
.ch-codeblock * {
  /* Fix horizontal scrollbars added to CodeHike blocks as a result of tailwind screwing up measurements */
  box-sizing: content-box;
}
```

This might be something that Code-Hike should include in its stylesheet.

I was able to demonstrate this in the `yarn dev`

After adding `* { box-sizing: content-box }`:
<img width="918" alt="Cole's screenshot of Code Hike Test - section 2022-07-26 at 07 57 41@2x" src="https://user-images.githubusercontent.com/2925395/181000608-a47a9fd5-806e-4bc4-8a33-0734bad0d5f9.png">

Before (**Bug**)
<img width="866" alt="Cole's screenshot of Code Hike Test - section 2022-07-26 at 07 57 19@2x" src="https://user-images.githubusercontent.com/2925395/181000627-764743e6-30f0-4b56-b8e6-d05b73bff91c.png">

**Comment by pomber** [comment]
Thank you. I didn't know Tailwind base was so "aggressive". I'll try to add some defensive CSS (like yours) to the default styles.

**Comment by pomber** [comment]
btw, can you tell me the browser and OS? scrollbars are weird

**Comment by colelawrence** [comment]
@pomber, I'm on Chrome 103 on macOS Intel

**Comment by colelawrence** [comment]
<img width="678" alt="Cole's screenshot of Prop types – Theatre js 2022-07-27 at 08 09 45@2x" src="https://user-images.githubusercontent.com/2925395/181243564-a414796c-662d-4dbd-9d30-76a61dc6c3af.png">

It appears that my work around does not really work for Firefox 102 on macOS Intel

As well, it appears that even with the fix, when there is no scroll-y, hovering over the scroll area and trying to scroll vertically still traps you from scrolling down the page. 🤷

**Comment by pomber** [comment]
> hovering over the scroll area and trying to scroll vertically still traps you from scrolling down the page

I fixed that on v0.7.2 (#241).

I'll try to debug the other issue. It would be great if you manage to isolate it inside the [playground](https://play.codehike.org).

**Comment by pomber** [comment]
I couldn't reproduce the `* { box-sizing: content-box }` issue. If you are able to consistently reproduce it please share a [playground](https://play.codehike.org/).

**Comment by pomber** [comment]
I think these are the elements that need `content-box`:

```css
[data-ch-panel] > div {
  box-sizing: content-box !important;
}
```

I'll add that to codehike's stylesheet later
