### ISSUE TITLE
Cannot execute mdx `run` on string with mdx included codehike code in next.js frontend

### ISSUE THREAD

**Issue by kliukovkin** [code-hike/codehike#247]
The issue is with such sample:

```js
import { run } from "@mdx-js/mdx";
import * as runtime from "react/jsx-runtime";
import { compile } from "@mdx-js/mdx";
import { remarkCodeHike } from "@code-hike/mdx";

const textTest1 = `
  \`\`\`python hello.py
  # mark[16:24]
  print("This is Code Hike")
  \`\`\`
`;

const code = await compile(textTest1, {
  outputFormat: "function-body",
  useDynamicImport: true,
  remarkPlugins: [[remarkCodeHike]],
})

const { default: Component } = await run(code, runtime)

console.log(Component);
```

When executing this code on backend everything works fine and I see in the console:

> [Function: MDXContent]

But the problem is that I'm running `compile`1 on the backend and return to the frontend string with code. Then, when I'm trying to call `run` I faced with an error:

<img width="957" alt="Screenshot 2022-07-28 at 14 29 55" src="https://user-images.githubusercontent.com/26343726/181494826-17c50abc-4658-4b86-980f-2d2598ea0ef0.png">

@pomber Do you know any workaround or how to solve this issue?

**Comment by kliukovkin** [comment]
Of course it is possible to return to frontend complete function text and then just convert it to a function, but maybe there is some more elegant solution than just `Function(textFromBackend)` =)

**Comment by pomber** [comment]
You probably need to disable [CodeHike's autoimport](https://codehike.org/docs/configuration#auto-import). See #222 for a similar issue.  

Let me know if it doesn't work.

**Comment by kliukovkin** [comment]
That works! Thank you @pomber !
