### ISSUE TITLE
Vfile TypeScript issues (v0.7.3-next.1)

### ISSUE THREAD

**Issue by MarkusWendorf** [code-hike/codehike#252]
The typescript resolution changes introduced by https://github.com/code-hike/codehike/pull/249 seems to surface an issue with the vfile / unified dependency.

StackBlitz forked from contentlayer example: https://stackblitz.com/edit/github-szrmjr?file=contentlayer.config.ts

Seems to be a version mismatch since between vfile v5 and vfile v4 (contents renamed to value) used by unified.

**Comment by pomber** [comment]
Thanks! I'll take a look later, any ideas on how to fix it?

**Comment by MarkusWendorf** [comment]
@pomber I think the issue is that content layer uses the unified v10 with vfile v5 and code hike is still on unified v9 with vfile v4. 

I guess upgrading unified to v10 would solve the issue.
