### ISSUE TITLE
Provide a means to auto-determine the height of CH.Code blocks with focus

### ISSUE THREAD

**Issue by zentol** [code-hike/codehike#258]
When embedding a file the only way to only show a part of the file is to use focus and manually specific a height.

While this works perfectly fine, it is quite brittle as changes to the focused area requires re-adjustments of the height, and it's also a bit tedious.

It would be nice if there'd be a way for CH to auto-determine the height to show everything in focus, or a sort-of heightPerLine setting that could be set in the configuration.

**Comment by pomber** [comment]
Yes, that's something I want to add. 

What do you thing about a `linesOfHeight` option?

````md
```js foo.js linesOfHeight=12
// from ./a-long-file.js
```
````

It could also work for focused lines:


````md
```js foo.js linesOfHeight=focus
// from ./a-long-file.js
```
````

**Comment by zentol** [comment]
Do I understand things correctly that `linesOfHeight=12` displays exactly 10 lines, and `linesOfHeight=focus` displays all lines between the first&last focused line?
If so, then that sounds great.
