### ISSUE TITLE
Add annotation to collapse lines

### ISSUE THREAD

**Issue by zentol** [code-hike/codehike#259]
When embedding somewhat larger pieces of code it can happen that the focused code is spread around quite a bit.
Currently everything between focused lines is being rendered, which causes code blocks to be larger than necessary.

It would be nice to have an annotation to hide certain lines, similar to how focus works.

**Comment by pomber** [comment]
Can you provide an example of your problem (a screenshot is ok)?  

You want to collapse lines that are between other focused lines, right?

**Comment by zentol** [comment]
In [this](https://play.codehike.org/#N4IgtgJgHiBcIB0B2BiABACQKYBscHtlkBRCASwBc0wsA6IpAA2YAcBPCgC3yTU9wK12aAGb4AxgFcAzgF4AbABoATABZYAZgCsyNHrQABAPIA3LACdzZCFl36WkgEY4y4tCfzW0N6RbIBDFwAvLAAKAGEeaUkacwAlLHF8cwgAHkcOLABtAF1FNAyKbJyAPjRzROSIfMi8RIpk1OIkK3F+CGIzJAoy-EkKAEo7fRH9LnN8AHdpNABJI2IocSwWCjIeNGBh0ZEyJEC0TqxutCwuqlk0AHMsCiPu0IqklIGAbm2R3f2cNABZW-8EH8FH81ABQJBaEuNwo-xBEP8j0qL3evFGei+B2wgIsM34OPMM2ht2xNkJSOeEDeH30fQotCSdXEFFCSCwk0OLVc7XuLLOxwo+Ro8OB-ny+LJ0gG1LRegAvgwRiwrCZgVhDudrrdeREojELAlKelMrl8oVimUnlUBmhxlMZvNFstVuteFtZaMKhRJOZePhHAAreq-fwsFgWWgVQEANUCkjCVpStFVOHjoQG+V5DJw-mkUtRIwVSG2AHoAFRlw5QCjmfzMmZcdUAaX8IgA1v4ALTK-AmaxYCBgkUg2hoMsl7bKsiqopoaQgtZuOGA0Va2Hg0W6pDRWKGqrGoqmgom0rlZFUzY0vRen28Nkc5cI0JX9H6RMQWgNFiudOKF+vs9KSEfxzDWNYeF-f9X3fWh8BEERfBZDMoPRGC1hoed-DAFhII9ACRgAZRrPYrmTOMsCMEQKSqT8yAwkFsIAFTYcN02lAt9CLUsKyrGs6woBt+DQGQLG7CY+xsQcJVxUdx0nFU1TnBdXEwLACRmGFSVxLcdwNc8D2KM0T0tc8bXdACb19NB71U9Tnzw-C9BhIirCQK4tPMWNUwTc98gwYgAEEABFiDiAB9Ri4gC8JiDCgjGICxjiGQhzHOc4i3I8ry03fPzApC8LIui2KAAUAriYgADlGPY7YuI9KcZ3VTDFzQFySLXdrMrUslsrCFC0Eibd9XifTzSPcbT1ytqMquPgeosMyX0su92Rm1yrmopNpPJAZaBzecPNCHa9pTNMMxm-wkCBFJwk4EDEOkWgAFVGIAMTCgAOGVC2QZhGAYEBFBAcQ8zgEAhAqPt2U7JJun8PYLE2NA7DAECrj2WA0E+lgoFeFGkDlIGQZ4XYrjgUAXDZSqYkcXE4BEQJfGB6RuEmSJ2AAIX6BokAZpmsGBxsaHBtGiisQJOxutsLBAOU5SAA) example I'd like to hide the `getEvent()`/`getMetaData()` methods, but not `out.collect(new EnrichedEvent(event, metadata, headers));` (below the first focused line).

I think collapsing _all_ unfocused lines wouldn't be desirable; you'd lose some context unless you expand the focus.
In the example above, the contents of of `deserialize` method are important for context, although we focus on a particular line.
Meanwhile, the 2 methods aren't relevant anymore, because they are covered elsewhere.

**Comment by pomber** [comment]
Ok, so you want something like:

````md
```python hello.py focus=6,24:35 collapse=10:22
# ...
```
````

**Comment by zentol** [comment]
yes, that would work.

**Comment by pomber** [comment]
https://codehike.org/docs/code/collapse
