### ISSUE TITLE
Support Dynamic Import ( next/dynamic )

### ISSUE THREAD

**Issue by NekoChanTaiwan** [code-hike/codehike#261]
![image](https://user-images.githubusercontent.com/47508893/183031730-775ca347-eabe-430b-8e57-e78f9dd690df.png)

| Lib | Version |
| ------------- | ------------- |
| @code-hike/mdx  | "0.7.3--canary.256.aefe40e.0"  |
| next-mdx-remote | "4.1.0" |
| typescript  | "4.7.4"  |

**Comment by NekoChanTaiwan** [comment]
I use `any` to skip the type check, and It's said :

![image](https://user-images.githubusercontent.com/47508893/183147586-1d86e711-ed23-4fd6-8910-203acaf5fa9f.png)

So I  try to pass the `CH.Code`, and got the same error :

![image](https://user-images.githubusercontent.com/47508893/183148079-96113bed-da24-4b31-8173-b9a44d72aa98.png)

Still finding other solution🥲

**Comment by pomber** [comment]
The problem is: 'next/dynamic' is for components, and `CH` is not a component, it's an object. So, I think, what you are trying to do is not possible.

**Comment by NekoChanTaiwan** [comment]
> The problem is: 'next/dynamic' is for components, and is not a component, it's an object. So, I think, what you are trying to do is not possible.`CH`

Thx for reply 🥲
