### ISSUE TITLE
link annotation support target='_blank'

### ISSUE THREAD

**Issue by nekochan0122** [code-hike/codehike#266]
![image](https://user-images.githubusercontent.com/47508893/184472502-65a1b90c-bc7a-41de-8951-5d83e659ab91.png)

```js
// link[7:14] https://codehike.org _blank <=== maybe can add this ( ?
const codehike = 'perfect'
```

**Comment by brianespinosa** [comment]
@NekoChanTaiwan it is possible to change the way links render in markdown using rehype/remark plugins.  I think [rehype-external-links](https://github.com/rehypejs/rehype-external-links) would work for your use case. It would also give you a way to safely add the [`rel` attribute, which is good to pay attention to for safety](https://web.dev/external-anchors-use-rel-noopener/).

**Comment by NekoChanTaiwan** [comment]
> @NekoChanTaiwan it is possible to change the way links render in markdown using rehype/remark plugins. I think [rehype-external-links](https://github.com/rehypejs/rehype-external-links) would work for your use case. It would also give you a way to safely add the [`rel` attribute, which is good to pay attention to for safety](https://web.dev/external-anchors-use-rel-noopener/).

Idk why this plugin is not working 🥲
![image](https://user-images.githubusercontent.com/47508893/184988816-30a09fc5-fb21-4621-b812-8240f609e633.png)

**Comment by brianespinosa** [comment]
Hmm. If you have this configured correctly, I'd have to go look at the code. It is possible that rehype is not processing comment metadata and that is being done manually in Codehike.

**Comment by pomber** [comment]
Yes, the rehype plugin won't work for this.  

Before adding this feature we need a good syntax to pass options to annotations. Maybe something like this:

```
// link[7:14] https://codehike.org target=_blank title="lorem ipsum"
```


but I want to make sure it scales with more annotations and options before implementing it.
