### ISSUE TITLE
Support for native Svelte

### ISSUE THREAD

**Issue by muellerzr** [code-hike/codehike#285]
Hi! I'm interested in using CodeHike for the documentation in a number of my own repos, and potentially integrate it into my companies as well (Hugging Face 🤗 ) for our examples, as I absolutely love the ScrollyCoding and everything in between! One issue though is that it can only be used with React, and our documentation is built on Svelte and Markdown ([mdsvex](https://mdsvex.pngwn.io/)).

Could it be possible to support Svelte natively? :)

**Comment by pomber** [comment]
Hi! I love Svelte but Code Hike uses a lot of React, so native Svelte support would mean a lot of work.

**Comment by may17** [comment]
@pomber just an idea: would it be possible to switch over to native web components? So, any framework could be supported?

**Comment by pomber** [comment]
Not possible without a lot of work. If I ever rewrite I'll consider multi framework support.

**Comment by texastoland** [comment]
Re. #333: I'd love to use it in Vue too if you ever attempt a rewrite. You could potentially compile a lightweight JSX dependency to web components then build higher level components on top.
