### ISSUE TITLE
not work after deployed to vercel

### ISSUE THREAD

**Issue by lili21** [code-hike/codehike#291]
I'm running the mdx compiler on the server side on each page request, it works fine on my local machine, but on on vercel. 

the error message 

```
no such file or directory, open '/var/task/node_modules/shiki/languages/abap.tmLanguage.json'

```

**Comment by pomber** [comment]
Hi, see https://github.com/code-hike/codehike/issues/283#issuecomment-1277017015

> this fixed the issue for me on getServerSideProps
> 
> // in your next.js page 
> export const config = {
>   unstable_includeFiles: ['node_modules/**/shiki/**/*.json'],
> };

**Comment by lili21** [comment]
I'm using the remix framework. what config should I apply?

**Comment by pomber** [comment]
should be fixed with `v0.8.0`, let me know how it goes

**Comment by lili21** [comment]
Could not resolve "@code-hike/mdx/dist/components.cjs.js"

I'm using it with [mdx-bundler](https://github.com/kentcdodds/mdx-bundler).

**Comment by pomber** [comment]
> Could not resolve "@code-hike/mdx/dist/components.cjs.js"
> 
> I'm using it with [mdx-bundler](https://github.com/kentcdodds/mdx-bundler).

Can you share more details? 
We have a remix example and a mdx-bundler example (in the examples folder), compare them with yours and check what's different

**Comment by lili21** [comment]
sure. I'm doing it on the server side.

```js
import { bundleMDX } from "mdx-bundler";
import { remarkCodeHike } from "@code-hike/mdx";
import theme from "shiki/themes/nord.json";

export const loader = async () => {
  const data = await fetchFromCRM();

  const result = await bundleMDX({
      source: data,
      mdxOptions(options, frontmatter) {
        options.remarkPlugins = [
          ...(options.remarkPlugins ?? []),
          [
            remarkCodeHike,
            {
              showCopyButton: true,
              theme,
            },
          ],
        ];

        return options;
    },
  });

  return { result }
}
```

**Comment by pomber** [comment]
hmm, you may need to use [`autoImport: false`](https://codehike.org/docs/configuration#auto-import)
