### ISSUE TITLE
Changing line-height doesn't work

### ISSUE THREAD

**Issue by pomber** [code-hike/codehike#295]
### Discussed in https://github.com/code-hike/codehike/discussions/294

<div type='discussions-op-text'>

<sup>Originally posted by **Archakov06** October 24, 2022</sup>
![image](https://user-images.githubusercontent.com/12086860/197461058-46aba3a8-a4c8-4a82-b153-9fa0a18b0690.png)

The code looks too compressed and I would like to make a small indent between the lines

I tried using line-height, but it turned out that the margins are set via the transform property</div>

**Comment by Archakov06** [comment]
there is no solution yet?
