### ISSUE TITLE
codehike makes problem with docusaurus and mermaid

### ISSUE THREAD

**Issue by blackPeppper** [code-hike/codehike#300]
codehike makes mermaid not work
![image](https://user-images.githubusercontent.com/93441520/201195180-226e095f-dc0f-4e98-9f6e-2c18c8bb4abc.png)
![image](https://user-images.githubusercontent.com/93441520/201195279-35866363-60ae-4dbe-acc5-4514fa716002.png)

[docusaurus](https://docusaurus.io/docs/markdown-features/diagrams#configuration)

**Comment by pomber** [comment]
There's a setting to [tell code hike to ignore some languages](https://codehike.org/docs/configuration#skip-languages), that should solve your problem.

There may be other issues, I think @JaKXz has Docusaurus + Code Hike + Mermaid working.

**Comment by JaKXz** [comment]
Yeah, I found that mdx-v2 and remark-mermaid don't play nice atm, so I published [`@jakxz/mdx-mermaid`](https://github.com/JaKXz/mdx-mermaid) to make it work.

@blackPeppper your mileage may vary / proceed at your own risk, etc. :)

**Comment by blackPeppper** [comment]
@JaKXz  should that work with codehike also right ?

**Comment by JaKXz** [comment]
Yes I am using it with codehike.

**Comment by blackPeppper** [comment]
after some work i did thanks guys

**Comment by jgarrow** [comment]
@JaKXz I'm also using Docusaurus and with Code Hike, but have been unable to get around the `require() of ES Module not supported` error when importing `mermaid` into my `docusaurus.config.js` (`const mermaid = require("@jakxz/mdx-mermaid");`). Is there a babel config that I need to add to get this to work?
