### ISSUE TITLE
How can I make preview feature only for HTML and CSS?

### ISSUE THREAD

**Issue by donghhan** [code-hike/codehike#302]
I can see preview feature is only workable for React's component-wise. 
Is there anyway I can make preview feature for HTML and CSS? Or maybe sometimes JS only?

**Comment by pomber** [comment]
You can use the `<CH.Preview>` component, it's not documented yet. But you can use any component inside

```jsx
```

**Comment by donghhan** [comment]
@pomber In the component that you just used `<CH.Preview show="/some/url" />`, prop `show` indicates the codesandbox preset repository? 
As there is no documentation on this, I still have no clue how to use with it.

**Comment by pomber** [comment]
The `show` prop is any url, it works like an iframe (well, it is an iframe). 

What are you trying to do? 

> Is there anyway I can make preview feature for HTML and CSS? Or maybe sometimes JS only?

With the Scrollycoding `preset` prop you can use most codesandbox as a template. You can use the `Vanilla` template from codesandbox for example.

**Comment by fedono** [comment]
@pomber could we use React Component in `<CH.Preview>` like below, and `<CreateForm />` will be render

```js
<CH.Preview frameless>
const CreateForm = require("./Form");
<CreateForm />
</CH.Preview>

```

**Comment by pomber** [comment]
> @pomber could we use React Component in `<CH.Preview>` like below, and `<CreateForm />` will be render

Yes, if the framework you are using allows it. See [mdx docs on how to import](https://mdxjs.com/docs/using-mdx/#components). But it's basically this:

```mdx
import CreateForm from './Form' 

...

<CH.Preview frameless>
  <CreateForm />
</CH.Preview>
```

**Comment by fedono** [comment]
@pomber Thanks, This project helps me a lot.

**Comment by RobbieTheWagner** [comment]
@pomber so is `CH.Preview` supposed to both show the code and render an example? It does not seem to show anything for me.

**Comment by pomber** [comment]
> @pomber so is `CH.Preview` supposed to both show the code and render an example? It does not seem to show anything for me.

can you provide an example? https://play.codehike.org/

**Comment by pomber** [comment]
it needs some height if you want to render the mini-brower view:

```
<CH.Preview style={{height: 200}}>
  <h1>Lorem ipsum</h1>
</CH.Preview>
```

**Comment by RobbieTheWagner** [comment]
> it needs some height if you want to render the mini-brower view:
> 
> ```
> <CH.Preview style={{height: 200}}>
>   <h1>Lorem ipsum</h1>
> </CH.Preview>
> ```

Oh I see! Thank you. Is there a way to display both the code and the preview? I would like people to be able to see the code and what it is rendered as, without needing to duplicate the code.
