### ISSUE TITLE
Is it possible to change the font size of the code block?

### ISSUE THREAD

**Issue by kk-min** [code-hike/codehike#304]
In my website, I used CSS and media query to change the font-size inside the code blocks depending on the screen size. After integrating code hike, I realized that this doesn't work, presumably because code-hike overrides the css styles.

This is especially important for smaller screens where I want the code to fit the width without creating a horizontal scroll bar as it makes the reading experience bad. Is there a way to do this that I am not aware of, or is it currently not supported?

**Comment by pn320** [comment]
You could probably add a custom-ch.css file and specify the media query rule, take a look at this [example](https://github.com/code-hike/not-stripe/blob/main/custom-ch.css). Not sure which selector would work for your use case, probably will take a little fiddling around but it's a start

**Comment by pomber** [comment]
You should be able to do it with CSS. I'll close this for now, reopen it if it's still not working, and share your CSS.
