### ISSUE TITLE
Tabs Hidden in Mobile View

### ISSUE THREAD

**Issue by parth-verma** [code-hike/codehike#306]
Link for reference: https://api-docs.frenzopay.com/docs/generating-signature

**Comment by parth-verma** [comment]
I see this 
<img width="277" alt="image" src="https://user-images.githubusercontent.com/22412980/208344710-74baddbf-2e07-468e-8282-62e6e93cc2f4.png">

**Comment by pomber** [comment]
Yes, I think the issue is that tabs should have a min-width and be horizontally scrollable.

> As a side note, we can also add a config option to hide the traffic lights in the window

You can hide them with CSS.
