### ISSUE TITLE
Stackblitz demo is not working 

### ISSUE THREAD

**Issue by ukeskin** [code-hike/codehike#311]
https://stackblitz.com/github/code-hike/codehike/tree/main/examples/nextjs

**Comment by pomber** [comment]
#308 should fix this

**Comment by pomber** [comment]
Still doesn't work. It may be related to stackblitz/webcontainer-core#935

**Comment by pomber** [comment]
The [nextra](https://stackblitz.com/github/code-hike/codehike/tree/main/examples/nextra?file=pages/index.mdx) and [mdx-bundler](https://stackblitz.com/github/code-hike/codehike/tree/main/examples/mdx-bundler) are having the same issue as [nextjs](https://stackblitz.com/github/code-hike/codehike/tree/main/examples/nextjs?file=pages/index.mdx).

The [contentlayer](https://stackblitz.com/github/code-hike/codehike/tree/main/examples/contentlayer) example has a memory issue (Error code: SBOX_FATAL_MEMORY_EXCEEDED) in stackblitz.

[Gatsby](https://codesandbox.io/s/github/code-hike/codehike/tree/main/examples/gatsby) doesn't work on stackblitz but it should work with codesandbox. It isn't working right now, but looks like a codesandbox general issue.

**Comment by pomber** [comment]
All working now, except [nextra](https://stackblitz.com/github/code-hike/codehike/tree/main/examples/nextra?file=pages/index.mdx) and [contentlayer](https://stackblitz.com/github/code-hike/codehike/tree/main/examples/contentlayer).

**Comment by ukeskin** [comment]
Yes 👍🏻 Thank you for your attention
