### ISSUE TITLE
Enabling lineNumbers in code block's meta

### ISSUE THREAD

**Issue by mahdiaslanimk** [code-hike/codehike#321]
Hi. Thanks for the great job, I really enjoy using code-hike. Sometimes I want to turn on lineNumbers for a specific code block and not for all of them. It would be great to add lineNumbers' state (on or off) to code block's meta instead of plugin options, like this:

```
'''js App.js focus=5:8 lineNumbers=on
import React from "react";
import { graphql } from "gatsby";

//...
'''
```

**Comment by pomber** [comment]
This is how you do it https://codehike.org/docs/ch-code#override-configuration

````mdx
<CH.Code lineNumbers={true}>

```python one.py
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
```

</CH.Code>
````

I know it's not the same but it's more flexible
