### ISSUE TITLE
Scrollycoding stopped sticking on nextra@2.2.13

### ISSUE THREAD

**Issue by yairhaimo** [code-hike/codehike#322]
Scrollycoding works fine except the code preview stops sticking on scroll.
Works fine in nextra v2.2.12 but stops working at v2.2.13.

https://stackblitz.com/edit/github-fpttkm-el4srd

**Comment by pomber** [comment]
Thanks.

It's probably the `overflow-x: hidden` Nextra added here: https://github.com/shuding/nextra/pull/1366/commits/fd020ca9d4834bb4ffa7ebdace2cb9d221b143c6#diff-8310a54b1ec9da38ed7c74e8c1328e33f07848d25bd9779811614642e3268747R51

Can you create an issue in the Nextra repo to see if they want to fix it there? `overflow-x: hidden` usually means `position: sticky` won't work. Here is [more info](https://www.terluinwebdesign.nl/en/css/position-sticky-not-working-try-overflow-clip-not-overflow-hidden/).
