### ISSUE TITLE
Focus and comment labels

### ISSUE THREAD

**Issue by gurkerl83** [code-hike/codehike#332]
Just a quick question, is a combination of focus and a comment label possible? I thought when you focus, it would be very nice to activate the corresponding comment label so the code itself does not have to include any comments. Anyway, thx for the great library you have built!

**Comment by pomber** [comment]
what do you mean by "activate the comment label"?

**Comment by gurkerl83** [comment]
When you hover over a link with the focus protocol set to line 3 it gets highlighted. 

```
line 1   function adipiscing(...elit) {
line 2      // label something something
line 3      console.log("hover me")            => would be nice if the comment shows on the right side, 
                                                  not requiring a separate hover over line 3 
line 5      return elit.map((ipsum) => ipsum.sit)
line 6   }
```
