### ISSUE TITLE
Replace buttons by tab component

### ISSUE THREAD

**Issue by mfranzke** [code-hike/codehike#344]
Just a passing suggestion (maybe not something to implement here in this PR, but just a thought).

I would maybe suggest using an accessible UI foundation package for the editor (which is essentially a Tabs component, I think?). There are quite a few [keyboard interactions](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) (e.g. roving focus) that are a bit tricky to get right when rolling your own.

For comparison's sake, here are a few that I know of, off the top of my head:

- https://react-spectrum.adobe.com/react-aria/useTabList.html
- https://reach.tech/tabs
- https://reakit.io/docs/tab/
- https://www.radix-ui.com/docs/primitives/components/tabs

_Originally posted by @melanieseltzer in https://github.com/code-hike/codehike/pull/341#discussion_r1150973712_

**Comment by melanieseltzer** [comment]
Thanks for opening this @mfranzke 👍

@pomber I would be happy to help work on implementation if you think having one of these packages as the base for the editor tabs is a good idea.

**Comment by stern-shawn** [comment]
+1 for this!

**Comment by pomber** [comment]
https://codehike.org/docs/code/tabs
