### ISSUE TITLE
Ability to copy just highlighted code

### ISSUE THREAD

**Issue by rachelnabors** [code-hike/codehike#351]
We have the copy button for the entire chunk of code, but I want to let learners copy just the code that is highlighted. Is this possible/in progress?

**Comment by pomber** [comment]
I was waiting for someone to ask for this one.

How do you think it should work for inline highlights? Do you mean highlighted using `focus` or using `mark`?

![image](https://user-images.githubusercontent.com/1911623/231756985-a410c6ac-b9c9-445d-bba7-11625983f651.png)

**Comment by rachelnabors** [comment]
This code:
<img width="506" alt="image" src="https://user-images.githubusercontent.com/236306/231839112-5c4263c2-58f7-4b37-9256-25ced6292af5.png">

Would add a copy button just to 
```
? Enter a name for the project reactamplified
The following configuration will be applied:
```

**Comment by pomber** [comment]
I added the copy button to the `mark` annotation (when you target one or more lines) but it's hidden by default. You need to display it with CSS:
```css
.ch-code-multiline-mark:hover .ch-code-button {
  display: block;
}
```

[Demo](https://playground-git-mark-copy-button-codehike.vercel.app/#N4IgtgJgHiBcIB0B2BiABACQKYBscHtlkBRCASwBc0wsA6IpAA2YAcBPCgC3yTU9wK12yFgCcySCgAoEIACqcyAZzTK0AYXwQsmMgGsssgJQjxkmfMUq1m7boPHk6MAENReqQEZYAJhNIxCWlZBTUbLR0MfUMQf0DzEKtVFVtI6McAs2DLMJSI+xi4rItQ6zy7KIdY5GZGBhAAGhAAYyUlOBAhUSwANzIsAHcAWmaeChcJLFE0YDRkNGo3AHMJWDQADhYoAG45pABfBlpmzhGIobAAVxwKMhxJi7c9WG4eqbRj09HtIYAjS4oFB4M3maHIShYOBcbDWvwIzT022Q+0aLR4ADMyEs4KB7kgsAA5S5gX5TdqwdEuHBKLBNJTcAaadgAIQBQKQcEp1NpIC4WBoHVcFCmZCpQwgTymIH2+yAA)
