### ISSUE TITLE
Add line numbers to individual hikes, not all on or off by default

### ISSUE THREAD

**Issue by rachelnabors** [code-hike/codehike#352]
Seems as though this is all on or off by default, but I'm using hikes for both code and terminal blocks—terminals don't have line numbers, but code editors do. Is there a way to selectively only show these on some hikes and not on others?

**Comment by pomber** [comment]
Yes. See [here](https://codehike.org/docs/ch-code#override-configuration)

~~~mdx
<CH.Code lineNumbers={true}>

```python one.py
print("Hello, world!")
print("Hello, world!")
print("Hello, world!")
```

</CH.Code>
~~~
