### ISSUE TITLE
Wordwrap lines of code

### ISSUE THREAD

**Issue by rachelnabors** [code-hike/codehike#353]
It would be great to be able to specify if code can be wrapped or not

**Comment by pomber** [comment]
not sure what you mean by "wrapping" here

**Comment by rachelnabors** [comment]
Like wordwrap, inside the boxes—breaking code onto multiple lines

**Comment by pomber** [comment]
It's difficult to add word wrap because of how code hike works. So it isn't planned for the near future (unless we found a clever way to add it without breaking other features).
