### ISSUE TITLE
Detect URLs for Links

### ISSUE THREAD

**Issue by nathanclevenger** [code-hike/codehike#356]
In many of our use cases, the code would have many embedded URLs and we really need the URLs to be clickable like you can with any JSON viewer plugin in your browser:

```json
{
  "🕵️ Inspect Vehicle": "https://inspect.vin/1C4HJXEN5MW592818",
  "🚛 Transport Vehicle": "https://transport.vin/1C4HJXEN5MW592818",
  "☁️ Connect Your Vehicle": "https://auth.vin/1C4HJXEN5MW592818",
  "🏦 Get Pre-Approved": "https://pre.approved.vin/1C4HJXEN5MW592818",
  "🕶️ Insure Vehicle": "https://ins.vin/1C4HJXEN5MW592818",
  "💸 Finance & Insurance": "https://fi.vin/1C4HJXEN5MW592818",
  "💸 Buy Vehicle": "https://buy.vin/1C4HJXEN5MW592818",
  "💸 Get Vehicle Service Contract": "https://vsc.vin/1C4HJXEN5MW592818"
}
```

Is this something that can be supported?  Is there any workaround in the meantime?  We can currently do this with Prism's Autolinker (https://prismjs.com/plugins/autolinker/), but we much prefer to use CodeHike if at all possible

**Comment by pomber** [comment]
The workaround is to use the link annotation: https://codehike.org/docs/annotations#link-annotation.

But we could add an `autolink` option.

**Comment by nathanclevenger** [comment]
@pomber we just upped our sponsorship and added a 1 time payment for additional support.  

An `autolink` option would be amazing, and if you are able to add that soon we can use CodeHike as the basis for the documentation for our several hundred APIs that are all hypermedia link driven ... adding support for this feature would be greatly appreciated.

**Comment by pomber** [comment]
I added a global `autoLink` option (false by default):

```js
mdxOptions = {
  remarkPlugins: [
    [
      remarkCodeHike,
      {
        theme: someTheme,
        autoLink: true,
      },
    ],
  ],
}
```

[Demo](https://playground-git-autolink-codehike.vercel.app/#N4IgtgJgHiBcIB0B2BiABACQKYBscHtlkBRCASwBc0wsA6IpAA2YCsBnfJZYZNNBEIF4NwK67geD+0ASSRsADlgDGVAGpYAFmXk4sA2PxCqKFGW1gB6U2WlzFtAG6XTARgDCAFgwApABrEAcgFYAWQB1fwBOACYADkcogQAaXj1BQGy9tAAVACcAQyt8TOU1DS0dPQMjE3MKHLyCuwcXd28-INDImLiQRKQ+AUBAMnFnTiQFKgBNfABXTLQVdU1tODLDYzNTbMmKVXqkJzdPHwCQ8OjYhKSBQB4NwDP9tABxLCoABUysAFoAQRkZTPxbLAgpQE5VW5h+dGy31+-wgOz2TUOrROHXOPWSgDdd8RSNjTLCzIoLIH6FaVCzSOGNA4tY7tM5dC5CQAdO2gAGKWXLyPEAMkk0mmHMWumBJLWADMyBT9s0jm1Tp1ur0mWgAEKTACe+PmJSWwoqawARurJQjqbKUfS0QJBMyHoUtXiAMpYTL2TloIZIarZRREkGk2xseTGqky5F05AAX2QzEYDC6IHkbDYcBAtHB9iwAHc3vJOBRspZnWhgPw0WBspkAOaWXRRGRQADcpYj8dzSHFlbgoBwhd8kzA+udydgouyODYWHiIDYqnwmaGMjVqsMnDgo-Hk5AGwo+AAMpYANZwaqTTdbLA0FPlijOshjt4QCsH50gCMRoA)

**Comment by nathanclevenger** [comment]
Amazing @pomber! Thank you so much!! 🙏
