### ISSUE TITLE
Code hike code block hides inside Tabs

### ISSUE THREAD

**Issue by ahigueratw** [code-hike/codehike#371]
Hi, I'm searching help on this issue. 

Inside `@twilio-paste/tabs` component the code sections from mdx component are hide on first load. The code block shows up when the window is resized. 

Maybe this is related to  https://github.com/code-hike/codehike/issues/319 and https://github.com/code-hike/codehike/issues/279 because the described behaviour is similar. 

I upload an example of this issue here https://stackblitz.com/github/ahigueratw/code-hike-tabs-example?file=pages%2Findex.jsx

**Comment by pomber** [comment]
Thanks for reporting, see https://github.com/code-hike/codehike/issues/372#issuecomment-1584272351
