### ISSUE TITLE
Expose a way to transform the copied code

### ISSUE THREAD

**Issue by oriolcastro** [code-hike/codehike#381]
Hi @pomber first of all thanks for this amazing library!

### Proposed feature

We are using Code Hike to display snippets of code in our dashboard/documentation. Most of them are _static_ but we have several use cases for snippets where we would like to use dynamic variables (ie to use the API_KEY for the logged-in user or a specific URL).

This is an example of the type of code snippet:

```bash
curl -X POST "{{VARIABLE_URL}}/some-endpoint" -H "Content-Type: application/json" -d
```

Since the code blocks need to be defined as _just strings_ we can not replace `VARIABLE_URL` dynamically as there is no such concept of placeholders in markdown. I thought to use the technique explained in this discussion https://github.com/code-hike/codehike/discussions/270. But, my efforts to use a `useEffect` didn't pay off as it is challenging to keep the DOM in sync when you do it outside of React. 

That is why I came back to use the _copy to clipboard_ feature. In our use case, it is ok to display the _placeholders_ in the code block and only replace them in the code the users would copy and paste elsewhere.

### Possible implementation

The proposed feature is to expose a way to transform the code content before it is copied to the clipboard. 

This is an example of how this could look like:

![example](https://github.com/code-hike/codehike/assets/17428673/baa5c456-0bf3-4710-be1d-65fa959c23af)

`transformCopyContent` is just a function that receives the content originally copied to the clipboard and returns a new string. 

The use of `replace` is just an example of how we could use this to pass variables from the React world via props as `<MyMDXImportedFile url={SOME_DINAMIC_VARIABLE} />` The API is flexible enough to offer different ways to use it.

I have a working implementation [here](https://github.com/oriolcastro/codehike/commit/8013233528ae76a863cf490b5c826751d52d1d47)

If you think this addition makes sense I would be happy to contribute it.

**Comment by pomber** [comment]
I'm going to try to add a `replace` prop to CH components.

````md
<CH.Code replace={{PLACEHOLDER: props.url}}>

```bash
curl -X POST "PLACEHOLDER/some-endpoint" -H "Content-Type: application/json" -d
```

</CH.Code>
````

would that work for you?

**Comment by oriolcastro** [comment]
Wow! Thanks for the super fast answer.

Yes, I think that would work for our use case. It was the alternate implementation I explored before settling for the function approach. But the object map is probably better as it doesn't open too much the API. 

Would the `replace` affect only the code copied to the clipboard or also the rendered content?

**Comment by pomber** [comment]
> Would the `replace` affect only the code copied to the clipboard or also the rendered content?

Both

**Comment by Dletta** [comment]
In this new replace attribute you are implementing, would it be possible to support multiple Placeholders?
```
<CH.Code replace={{PLACEHOLDER1: props.url, PLACEHOLDER2: props.path}}>
```
I am asking since I know I would need to be able to add multiple replacements for my documentation.

**Comment by pomber** [comment]
> In this new replace attribute you are implementing, would it be possible to support multiple Placeholders?

Yes. 

I'm working on an annotations refactor. I'll try to add the replace prop after that.
