### ISSUE TITLE
Make CH.Spotlight mobile responsive

### ISSUE THREAD

**Issue by MorningLit** [code-hike/codehike#387]
Hi! Thanks for creating this amazing library, I am really loving it so far.

I created this issue because I am wondering if it is possible to make the CH.Spotlight mobile responsive?
![image](https://github.com/code-hike/codehike/assets/57279935/21c0fe4e-14c5-4f52-8b50-931a05371429)
I've created an article with it and it doesn't look the best on mobile 🙁 
Maybe one possible solution is to make the code appear below the sections when there is not enough space?

**Comment by pomber** [comment]
👍 
we should do the same as with Scrollycoding and fallback to a static version of the component

**Comment by DanielFGray** [comment]
> +1 we should do the same as with Scrollycoding and fallback to a static version of the component

I have a horizontal spotlight component that works great on mobile, about half-way down the page here: https://danielfgray.com/articles/ez-react-forms

Maybe the fallback behavior can be controlled somehow?

**Comment by pomber** [comment]
Ideally, all the components should have a static version, not only for mobile but also for print, and for readers that don't like the interactivity.  

The idea is to use `staticMediaQuery` to control when to show the static version. It will be possible to set it at the component level. See [this issue](https://github.com/code-hike/codehike/issues/390).
