### ISSUE TITLE
Problem with copy button overlapping text

### ISSUE THREAD

**Issue by dsalazarm** [code-hike/codehike#411]
Hello:
We're seeing a weird behavior when the 1st line of code is long enough, the copy button overlaps with the text.

I'm attaching some screenshots:

- Current behavior:
<img width="629" alt="Screenshot 2023-10-26 at 8 42 39 AM" src="https://github.com/code-hike/codehike/assets/33073119/3a05ac9e-e65c-44c2-a3b8-8806deeec6db">

- Issue:
<img width="628" alt="Screenshot 2023-10-26 at 8 50 00 AM" src="https://github.com/code-hike/codehike/assets/33073119/f337cd27-d0f5-4d82-aebf-a429c1b65ac4">

I found that there is a 0 value for top in this:
https://github.com/code-hike/codehike/blob/14554f722aecfcada4e93eb6e786de052ddc3681/packages/mdx/src/smooth-code/smooth-container.tsx#L134

if we add, let's say 5px to this property, it will look like this:
- 5px top value:
<img width="627" alt="Screenshot 2023-10-26 at 8 52 37 AM" src="https://github.com/code-hike/codehike/assets/33073119/e6e4d2ab-0ec3-4ed5-9fff-2d132a569a6a">

- or with 10px:
<img width="627" alt="Screenshot 2023-10-26 at 9 48 45 AM" src="https://github.com/code-hike/codehike/assets/33073119/83d6dd50-f57f-4f3c-9557-4e422ffc84f7">

- Another option is changing the top property for .ch-code-button to 5px:
<img width="682" alt="Screenshot 2023-10-26 at 9 51 25 AM" src="https://github.com/code-hike/codehike/assets/33073119/04c5a2b5-25d9-4d62-ab88-22509550957c">

What do you think its the best option for this?

I can create a PR once we make a final decission

**Comment by Nctawade** [comment]
I think last one "ch-code" makes more sense
