### ISSUE TITLE
How to use Scrollycoding with images

### ISSUE THREAD

**Issue by Usey95** [code-hike/codehike#415]
Hi, is there any way to present images instead of code blocks using CH.scrollycoding? Just like [this](https://pomb.us/build-your-own-react/)
<img width="1263" alt="image" src="https://github.com/code-hike/codehike/assets/15168138/79178ea3-d94e-4e9c-adf4-b31299fc8f30">

**Comment by pomber** [comment]
It is possible but not easy. The next version will make it much easier.
