### ISSUE TITLE
Locking demos till 5 people pay $19/mo EACH is very counter-productive

### ISSUE THREAD

**Issue by onexdata** [code-hike/codehike#418]
I can't even tell if I *want* to sponsor codehike because your demos explaining how it even basically works is locked until enough people pay for each demo individually. Seems really counter-intuitive?

My first intuition is "Well, I can't quickly learn how it works unless I pay $19/mo... more than a YouTube premium account that can give me walk throughs for literally everything... so codehike will probably die from greed, as that is a really bad basic idea, and goes against the fabric of open source, and that idea appears on their home page, I'll wait for the next code walk through effort".

But then I saw literally GitHub is sponsoring you guys, so now it just feels really greedy and crazy, i.e. you must be good, but still locking basic knowledge about what it is? Like you're wasting human life, forcing people to read 10-100x more, wasting time of everyone that sees your project, hurting them, on purpose, even though you went through the effort to demo how it works, you lock it behind a group-effort pay-wall, and not even one person can solve it, it takes FIVE people to solve it for EACH demo... that feels... hopelessly nasty? Like you've introduced microtransactions to basic knowledge in open source.

If people copy this, through the power of wasted microlives in reading more difficult documentation, you'll literally be responsible for killing agregate people.

Please stop this?

**Comment by pomber** [comment]
The [new website](https://v1.codehike.org/) won't have locked demos. Hopefully, I can ship it before the current website kills anyone.
