### ISSUE TITLE
Using v1.0 (beta) with Nextra

### ISSUE THREAD

**Issue by lukecd** [code-hike/codehike#421]
First of all, thanks so much for this package. I heard it mentioned on the API The Docs podcast and I'm working to get it integrated into our docs now. 

Do you have a guide showing how to use the current 1.0beta with Nextra? I'm struggling to make it work. Thanks!

**Comment by pomber** [comment]
there's a PR with a nextra example https://github.com/code-hike/examples/pull/6, but it's currently blocked by an issue in nextra.

btw, do you have a link to the podcast?

**Comment by lukecd** [comment]
Ahh ok, I'll work off the sample repo you have for now. For the podcast, it was a longer podcast broken down into two parts. Both parts mention Code Hike

https://apithedocs.org/podcast/reactdev-and-storyboarding-rachel-lee-nabors
https://apithedocs.org/podcast/install-ways-check-overall-health-portal-conversation-rachel-lee-nabors
