### ISSUE TITLE
Showing Line Numbers

### ISSUE THREAD

**Issue by lukecd** [code-hike/codehike#423]
Is showing line numbers currently supported? The docs are still blank

https://v1.codehike.org/docs/code/line-numbers

Thanks!

**Comment by pomber** [comment]
It's supported using [custom Line components](https://v1.codehike.org/docs/concepts/annotations#customizing-line-and-token-components). I'll add an example really soon.

**Comment by pomber** [comment]
Updated https://v1.codehike.org/docs/code/line-numbers
