### ISSUE TITLE
Annotation handlers always applied?

### ISSUE THREAD

**Issue by aromko** [code-hike/codehike#440]
Hey, another thing I struggling with when using annotations that they are always applied even when I'm not using annotation on a codeblock. I'm using v1.0.0.

For example I copied the focus code from https://codehike.org/docs/code/focus.

Then I add it as handler in my component:

```
import { type HighlightedCode, Pre } from 'codehike/code';
import { focus } from '@/utils/codehike/focus';

function CodeHikeWrapper({ codeblock }: { codeblock: HighlightedCode }) {
  return <Pre code={codeblock} handlers={[focus]} />;
}

export default CodeHikeWrapper;
```

In my mdx file I have a codeblock:

```
html use-v1
<select>
  <option value="backlog">Backlog</option>
  <option value="in-progress">In Progress</option>
  <option value="in-review">In Review</option>
  <option value="done">Done</option>
  <option value="wont-do">Won't do</option>
</select>
```

Like you can see I have no annotation with focus on it but the opacity seems to be applied. 

```
...
Line: props => (
    <InnerLine
      merge={props}
      className="px-2 opacity-50 data-[focus]:opacity-100"
    />
  ),
...
```

How can I avoid this? I would think the focus stuff is only applied when using focus annotation e.g. `// !focus(1:2)`.

Thanks in advance.

**Comment by pomber** [comment]
there is:

```tsx
const focus: AnnotationHandler = {
  name: "focus",
  onlyIfAnnotated: true,
  ...
}
```

I should add it to the example

**Comment by aromko** [comment]
Ah perfect. Thank you.
