### ISSUE TITLE
TypeError: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

### ISSUE THREAD

**Issue by donghhan** [code-hike/codehike#444]
I produced my personal devblog repository with [Stackblitz](https://stackblitz.com/~/github.com/donghhan/apensia-nextra-devblog). You can click and view how it shows. 

Anyway, I tried to follow the example code of [code-mentions](https://codehike.org/docs/code/code-mentions) as it shown on documentation. However, `Code` component is asynchronous, which afaik it does not make sense normally as React component should be synchronous. 

My following dependencies are as follows. 

```json
"dependencies": {
    "codehike": "^1.0.0",
    "lucide-react": "^0.436.0",
    "next": "^14.2.3",
    "nextra": "^2.13.4",
    "nextra-theme-docs": "^2.13.4",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "remove": "^0.1.5",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@types/node": "20.12.7",
    "@types/react": "^18.3.4",
    "autoprefixer": "^10.4.19",
    "patch-package": "^8.0.0",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.3",
    "typescript": "5.4.5"
  }
```

I downgraded `nextra` from `3.0.0-alpha` to `2.X.X` since it seems to be nightly build yet so that I wanted to avoid any unexpected error. 

If I change my `code.tsx` file within `/components` folder, as synchronous, error disappears but then I don't get the effect that I was expecting. 

<img width="884" alt="image" src="https://github.com/user-attachments/assets/611d254c-4c67-4195-bbb2-a9ec2c57235e">

If I change `Code` component as below as asynchronous, 

```tsx
export async function Code({ codeblock }: { codeblock: HighlightedCode }) {
  const highlighted = codeblock;

  return (
    <Pre
      code={highlighted}
      handlers={[callout, className, hover]}
      className="border border-zinc-500/50 rounded py-2 px-4 my-4"
      style={codeblock.style}
    />
  );
}
```

I get the error as below 

> Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

Am I missing something? Or configuration might has been wrong?

**Comment by pomber** [comment]
hi! `async` components are only for frameworks supporting RSC, if you are using `nextra` you shouldn't have `async` components, see [here in the docs](https://codehike.org/docs/concepts/code#react-server-components)

I opened the Stackblitz link but I don't see the `hover` handler

**Comment by donghhan** [comment]
Forget about the Stackblitz example. It seems to be not applying update that I made. 

In your [documentation](https://codehike.org/docs/concepts/code#react-server-components) of `page.tsx` code, 

```tsx
import Content from "./content.md"

export default function Page() {
  return <Content components={{ MyCode }} />
}
```

You are actually importing the specific MDX content file in `Page` component every single time. Does this mean if I have hundreds of MDX content pages that I want to apply for code-mentions effect, do I have to do it manually? 

If so, I think I need to drop nextra...

**Comment by pomber** [comment]
That's just an example, don't take it literally, different frameworks load the markdown differently. In nextra you use the `theme.config.jsx` to pass the `components: {MyCode}`.

**Comment by donghhan** [comment]
> That's just an example, don't take it literally, different frameworks load the markdown differently. In nextra you use the `theme.config.jsx` to pass the `components: {MyCode}`.

@pomber I can see that's the way how we can include [Custom MDX components](https://nextra.site/docs/docs-theme/theme-configuration#mdx-components) in Nextra. But still, `MyCode` should not be asynchronous. So basically as you have written on your example code, I might need to configure `highlight` during compilation process, but then some of the effects might seem to work not properly. 

Will close this issue at this moment and will do more research on this. As you have integrated with Nextra version of alpha version 3, some of the features could be possibly deleted by the author.

**Comment by pomber** [comment]
Just for clarification, the only examples that don't work without async components are the [transpile](https://codehike.org/docs/code/transpile) and [typescript](https://codehike.org/docs/code/twoslash) examples. The rest should work after you [adapt them](https://codehike.org/docs/concepts/code#react-server-components).
