### ISSUE TITLE
Token transitions color transition errors

### ISSUE THREAD

**Issue by jyecusch** [code-hike/codehike#457]
Hey, first this library is incredible.

I've noticed some odd behavior with colors when using token transitions, where the tokens end up the wrong color.

Here is an example recorded on the Scrollycoding page on the docs:

https://github.com/user-attachments/assets/318b77ca-dc94-4c2c-b1c4-e3a9a37a0a0a

This is in Chrome, but the same occurs in Firefox and Safari.

I can see something similar on the [Token Transitions](https://codehike.org/docs/code/token-transitions) page, where the opening parenthesis in `if (n == 0)` turns blue when switching from scala to python and back to scala.

![Token_Transitions___Code_Hike](https://github.com/user-attachments/assets/d72fed0a-9fdf-4eae-9f49-955e89eb329a)

The strange thing is that if you inspect those <span> elements, they have the correct color set on their inline style.

**Comment by tatasadi** [comment]
I can confirm this issue. I'm noticing many incorrect colors in various places. Here are one example:

![grafik](https://github.com/user-attachments/assets/d8822fce-fb1f-428b-8f71-380e8c353dd3)

**Comment by tjholm** [comment]
Have found changing the `fillMode` of the the animations from `both` to `backwards` seems to solve the color issue, at least for me. Still need to do more testing.

see `componentDidUpdate()` of `SmoothPre`:
https://codehike.org/docs/code/token-transitions

**Comment by pomber** [comment]
I think it's a problem with React reusing the elements for different tokens (and keeping the transition state). For example, forcing React to re-create all elements should fix it:

```tsx
export const tokenTransitions: AnnotationHandler = {
  name: "token-transitions",
  PreWithRef,
  Token: (props) => (
    <InnerToken
      merge={props}
      style={{ display: "inline-block" }}
      key={Math.random()} // HACK 
    />
  ),
}
```

I'll try to find a good solution, ideally making React reset any token transition before calculating the new colors.
