### ISSUE TITLE
[mdx] Add `<CH.Trace/>` component

### ISSUE THREAD

**Issue by pomber** [code-hike/codehike#81]
Like in http://worrydream.com/#!/LearnableProgramming or https://www.replay.io/

https://user-images.githubusercontent.com/1911623/141290706-21be3f6c-0c2e-47f2-b998-369529ca76ba.mp4

**Comment by texastoland** [comment]
Related:

- https://github.com/fullstackio/choc (same as video)
- https://github.com/ncase/joy (inspired by Logo)
