### ISSUE TITLE
Error: Invalid number "7,12" in focus string

### ISSUE THREAD

**Issue by DanielFGray** [code-hike/codehike#91]
I was trying to use multiple ranges in a bg/focus attribute, I tried this:
```
```javascript src/index.js bg=7,12:17,29:31,34
```
but I get the error `Error: Invalid number "7,12" in focus string`.

Am I using the wrong syntax or is this not yet supported?

**Comment by pomber** [comment]
That's a bug (for `bg`, for `focus` I think it works).

One work-around at the moment is to use comment annotations:

~~~md

```js src/index.js
// bg
function lorem(ipsum, dolor = 1) {
  const sit = ipsum == null && 0;
  // bg(1:2)
  dolor = sit - amet(dolor);
  return sit ? consectetur(ipsum) : [];
}

// bg(1:4) green
function adipiscing(...elit) {
  console.log(elit);
  return elit.map((ipsum) => ipsum.sit);
}
```
~~~
